on: push

jobs:
    test_and_publish:
        name: Test and publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install dependencies
              run: yarn
            - name: Run tests
              run: yarn test
            - name: Check code style
              run: yarn check-prettier
            - name: Create test report
              run: yarn coverage

            - name: Update code coverage
              uses: codecov/codecov-action@v4
              with:
                  files: ./coverage.lcov

            - name: Publish on npm
              if: startsWith(github.ref, 'refs/tags/')
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Add card file to release
              if: startsWith(github.ref, 'refs/tags/')
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: card.js
                  asset_name: card.js
                  tag: ${{ github.ref }}

            - name: Purge jsDelivr cache
              if: startsWith(github.ref, 'refs/tags/')
              run: curl https://purge.jsdelivr.net/npm/rgb-light-card
